language: node_js
node_js:
  - "6"
  - "5"
  - "4"
branches:
  only:
    - master
    - dev
install:
  - npm install
before_script:
  - npm run lint
  - npm run lint:test
  - npm test:coverage
script:
  - npm run build
